global:
  scrape_interval: 15s  # Intervalo de muestreo global

rule_files:
  - "alert.rules.yml"  # Ruta al archivo con las reglas de alerta

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
